### ISSUE TITLE
Pi Zero Error (Not Working)

### ISSUE THREAD

**Issue by robdixn** [torch2424/piStreamRadio#17]
Got everything installed on my Pi Zero and when I ran ./startStream.sh I got the following error which kept looping until I hit Ctrl+C to stop it:

High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.23.8; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes
./startStream.sh: line 103: 17409 Terminated              ( ./runFfmpeg.sh $(cat "$CURRENT_GIF_PATH") "$STREAM_TEXT_PATH" & sleep 2; CURRENT_GIF="$STREAM_GIF_PATH$(date +%s).gif"; echo "$CURRENT_GIF" > "$CURRENT_GIF_PATH"; RANDOM_GIF=$(./getFileFromDir.sh "$GIF_DIRECTORY"); ./optimizeGif.sh "$RANDOM_GIF" "$CURRENT_GIF" & wait )

mpg123: death by SIGTERM
./runFfmpeg.sh: line 49: 17417 Illegal instruction     ffmpeg -f alsa -ac 2 -i hw:Loopback,1,0 -fflags +genpts -ignore_loop 0 -r $VIDEO_FPS -i "$GIF" -s $VIDEO_RESOLUTION -vf "[in]drawtext=   text=:'$STREAM_TITLE':   fontfile=${VIDEO_FONT}:   fontsize=$FONT_SIZE:   bordercolor=$FONT_BORDER_COLOR: borderw=1: fontcolor=$FONT_COLOR:   y=$FONT_TITLE_Y_POS: x=w-mod(max(t\,0)*(w+tw)/$FONT_TITLE_SCROLL_SPEED\,(w+tw)),   drawtext=fontfile=${VIDEO_FONT}:   fontsize=$FONT_SIZE:   fix_bounds=true:   bordercolor=$FONT_BORDER_COLOR: borderw=1: fontcolor=$FONT_COLOR:   textfile=$STREAM_TEXT_PATH: y=$FONT_MUSIC_Y_POS: x=$FONT_MUSIC_X_POS[out]" -vcodec h264_omx -x264opts keyint=$KEYINT:min-keyint=$KEYINT:scenecut=-1 -b:v $VIDEO_BIT_RATE -preset veryfast -pix_fmt yuv420p -c:a libfdk_aac -b:a $AUDIO_BIT_RATE -bufsize 960k -ar $AUDIO_SAMPLE_RATE -f flv $STREAM_URL
ffmpeg: no process found

How do I fix this because I have no idea what 'no process found' means?

**Comment by torch2424** [comment]
Hello,

So it seems that FFmpeg wasn't installed correctly. In the README, I mentioned that this does not work with Raspberry pi 1. Which would include Pi Zero, though I should probably explicitly state that.

However, if you are really motivated to get things working, try running `./additionalScripts/compileFFmpeg.sh`. It will take about an hour to complete, because it will build the required FFmpeg for piStreamRadio, but for your raspberry pi. 

This **may** get things working but no promises.

Let me know if that helps 😄

**Comment by robdixn** [comment]
Will be trying that today...

![image](https://user-images.githubusercontent.com/8268467/30854481-b015c8f0-a2a9-11e7-9d22-e8eb0db88398.png)

Once it has finished compiling, do I just re-run the ./startStream.sh file once I have re-configured the config file?

**Comment by robdixn** [comment]
Yeah it's still throwing them errors even after that FFmpeg compiler.
Oh well, that's a shame, I guess the Pi Zero isn't powerful enough for this.
Thanks anyway.
