### ISSUE TITLE
[alsa@0x36e8b60] ALSA buffer xrun.

### ISSUE THREAD

**Issue by MattDuskson** [torch2424/piStreamRadio#20]
After a while I always end up get this error message causing cuts and stopping the broadcast.

![image](https://user-images.githubusercontent.com/4438898/31866713-0ebd032a-b784-11e7-910c-e53e77071f4d.png)

**Comment by torch2424** [comment]
Hello! That usually happens because the pi is having trouble keeping up with the stream. Which Pi are you running on? And you could possibly try putting smaller gifs in you `radioFiles/gifs`. And perhaps change the `MAX_GIF_SIZE` in your `radioFiles/config.sh`

**Comment by torch2424** [comment]
So, this confirmed by skilikis (sorry if I spelled it wrong, I'm on my phone) to be a network issue. If you run this into `/dev/null` this will not happen.

The only solution is to make sure your router gives your pi the highest network priority, and maybe call your ISP :)
