### ISSUE TITLE
./startStream.sh on boot

### ISSUE THREAD

**Issue by robsd** [torch2424/piStreamRadio#22]
Just got a new Pi 3 and this project works flawlessly on it.

I've set up a samba server on the Pi to add music and gifs over my local network. This runs automatically at boot/startup of the Pi.

One thing I'd like to be able to do is run the ./startStream.sh script automatically at boot/startup of the Pi.

Is this possible? How would I go about doing this? (I have tried rc.local and that doesn't seem to work)

**Comment by torch2424** [comment]
Hello! 

Nice! I am glad you got it all set up and stuff nicely! Would you mind sharing me your stream link? I like to check out streams that use the project if that is alright :)

Also, I use Systemd to accomlish this for me. I have a personal template for systemd services at: https://github.com/torch2424/dotFiles/blob/master/.files_templates/systemctl.service

So, create a file at the project root, for example `vim piStreamRadio.service` yours will look something like: 

```
# How to create systemd services: http://neilwebber.com/notes/2016/02/10/making-a-simple-systemd-file-for-raspberry-pi-jessie/
# Digital ocean on a mongodb service: https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04
# Original Template: https://github.com/torch2424/dotFiles/blob/master/.bash_templates/systemctl.service 
# Copy the file to /etc/systemd/system
[Unit]
Description=Torch2424 Template for simple systemctl service
After=network.target

[Service]
Type=simple
User=pi
WorkingDirectory=/home/pi
ExecStart=/bin/bash --login -c 'source /home/pi/.bashrc; cd [Directory to run] && ./startStream.sh'
Restart=always

[Install]
WantedBy=multi-user.target
```
Please notice how I am running this all through another bash session where I am sourcing the .bashrc, this is to ensure it runs as it normally would if you were to ssh in and stuff. 

Then, run the commands:

```
sudo cp piStreamRadio.service /etc/systemd/system
sudo systemctl start piStreamRadio
```

Then wait a while, and see if the stream starts and works. If not, you can check the logs with the command: 

```
sudo journalctl -u piStreamRadio
```

If it does work, enable this to start at boot with:

```
sudo systemctl enable piStreamRadio
```

Also, your mileage may vary, I wrote this on the top of my head, for an in depth guide, try: http://neilwebber.com/notes/2016/02/10/making-a-simple-systemd-file-for-raspberry-pi-jessie/

**Comment by torch2424** [comment]
Closing this as we have version 2.0.0 coming out soon. Please use that once it is release 😄 

Though, the systemctl stuff still applies!
