### ISSUE TITLE
Not working on Pi 2 Model B

### ISSUE THREAD

**Issue by skykery** [torch2424/piStreamRadio#23]
`--------------------------------------------------
Playing next song...
--------------------------------------------------

High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.23.8; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes

mpg123: death by SIGTERM
 ./startStream.sh: line 103: 14167 Terminated              ( ./runFfmpeg.sh $(c
t "$CURRENT_GIF_PATH") "$STREAM_TEXT_PATH" & sleep 2; CURRENT_GIF="$STREAM_GIF_
ATH$(date +%s).gif"; echo "$CURRENT_GIF" > "$CURRENT_GIF_PATH"; RANDOM_GIF=$(./
etFileFromDir.sh "$GIF_DIRECTORY"); ./optimizeGif.sh "$RANDOM_GIF" "$CURRENT_GI
" & wait )
  ./runFfmpeg.sh: line 49: 14174 Illegal instruction     ffmpeg -f alsa -ac 2 -
 hw:Loopback,1,0 -fflags +genpts -ignore_loop 0 -r $VIDEO_FPS -i "$GIF" -s $VID
O_RESOLUTION -vf "[in]drawtext=   text=:'$STREAM_TITLE':   fontfile=${VIDEO_FON
}:   fontsize=$FONT_SIZE:   bordercolor=$FONT_BORDER_COLOR: borderw=1: fontcolo
=$FONT_COLOR:   y=$FONT_TITLE_Y_POS: x=w-mod(max(t\,0)*(w+tw)/$FONT_TITLE_SCROL
_SPEED\,(w+tw)),   drawtext=fontfile=${VIDEO_FONT}:   fontsize=$FONT_SIZE:   fi
_bounds=true:   bordercolor=$FONT_BORDER_COLOR: borderw=1: fontcolor=$FONT_COLO
:   textfile=$STREAM_TEXT_PATH: y=$FONT_MUSIC_Y_POS: x=$FONT_MUSIC_X_POS[out]"
vcodec h264_omx -x264opts keyint=$KEYINT:min-keyint=$KEYINT:scenecut=-1 -b:v $V
DEO_BIT_RATE -preset veryfast -pix_fmt yuv420p -c:a libfdk_aac -b:a $AUDIO_BIT_
ATE -bufsize 960k -ar $AUDIO_SAMPLE_RATE -f flv $STREAM_URL
ffmpeg: no process found
mpg123: no process found
generateGif: no process found

--------------------------------------------------
Playing next song...
--------------------------------------------------`

After your steps, when i'm starting the startStream.sh it keeps crashing. I'm running Raspbian stretch.

**Comment by AndreasWebdev** [comment]
```
ffmpeg: no process found
mpg123: no process found
generateGif: no process found
```

It seems like either you did not install all modules or they themselves crashed.

Can you provide us line 49 of ./runFfmpeg.sh?

**Comment by torch2424** [comment]
Oh what! Thanks @AndreasWebdev for helping out! Just saw this.

Yes, I totally agree, something didn't install right, try running the install scripts again :)

**Comment by skykery** [comment]
```
Testing FFmpeg...
 
 
./installDeps.sh: line 46:   829 Illegal instruction     ffmpeg
 
piStreamRadio is now finished installing!

```
after running the install sh

**Comment by torch2424** [comment]
Oh, it seems something is wrong with installing ffmpeg. Perhaps try compiling it from source?

Try running `./additionalScripts/compileFFmpeg.sh` from the project root directory. This is going to take a long while however, so definitely be prepared for that.

However, since mpg123 is being killed, that is good, as it means it is installed.

**Comment by skykery** [comment]
Cloning into 'ffmpeg-source'...
remote: Counting objects: 535947, done.
remote: Compressing objects: 100% (108508/108508), done.
remote: Total 535947 (delta 427995), reused 534061 (delta 426375)
Receiving objects: 100% (535947/535947), 127.19 MiB | 625.00 KiB/s, done.
Resolving deltas: 100% (427995/427995), done.
Checking out files: 100% (6713/6713), done.
Unknown option "--disable-vda".
See ./configure --help for available options.
Makefile:2: ffbuild/config.mak: No such file or directory
Makefile:40: /tools/Makefile: No such file or directory
Makefile:41: /ffbuild/common.mak: No such file or directory
Makefile:90: /libavutil/Makefile: No such file or directory
Makefile:90: /ffbuild/library.mak: No such file or directory
Makefile:92: /fftools/Makefile: No such file or directory
Makefile:93: /doc/Makefile: No such file or directory
Makefile:94: /doc/examples/Makefile: No such file or directory
Makefile:157: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
Makefile:2: ffbuild/config.mak: No such file or directory
Makefile:40: /tools/Makefile: No such file or directory
Makefile:41: /ffbuild/common.mak: No such file or directory
Makefile:90: /libavutil/Makefile: No such file or directory
Makefile:90: /ffbuild/library.mak: No such file or directory
Makefile:92: /fftools/Makefile: No such file or directory
Makefile:93: /doc/Makefile: No such file or directory
Makefile:94: /doc/examples/Makefile: No such file or directory
Makefile:157: /tests/Makefile: No such file or directory
make: *** No rule to make target '/tests/Makefile'.  Stop.
./additionalScripts/compileFFmpeg.sh: command substitution: line 51: syntax error near unexpected token `('
./additionalScripts/compileFFmpeg.sh: command substitution: line 51: `ffmpeg version N-87246-g260ea7a7b3-ntd_20150128 Copyright (c) 2000-2017 the FFmpeg developers
`

**Comment by torch2424** [comment]
Can you try and remove the "--disable-vda" from the `./additionalScripts/compileFFmpeg.sh` file?

My apologies you are having so much trouble with this! I may also end up suggesting just starting from scratch with a fresh image install.

**Comment by skykery** [comment]
I did it and vda option was the problem, now ffmpeg is compiled. Seems that "--disable-vda" option wasn't in ffmpeg cfg options.

**Comment by torch2424** [comment]
Thank you for reporting this, I'll make an issue to get that fixed :)
