### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by skykery** [torch2424/piStreamRadio#26]
Can you build a docker image arm based with the project?

**Comment by torch2424** [comment]
Hello! Honestly, I've tried getting into the docker ecosystem in the past, but never could get too into it. 

However, this is before things like docker compose existed, and give docker a third chance was on my TODO list, so I'll definitely keep this in mind, and use this project as a stepping board into docker if I get to it :)

**Comment by luccyrobert1212** [comment]
Sir Do you create a same project for Ubuntu also

**Comment by torch2424** [comment]
We have version 2.0.0 coming out, so this would require a different setup. Please feel free to comment if there is still interest in this. Thank you!
