### ISSUE TITLE
streaming to restream.io

### ISSUE THREAD

**Issue by Kikyuo** [torch2424/piStreamRadio#27]
hi i tried to stream via restream.io to twitch and youtube but wasnt really working after each song he had to like reconnect any advice what i can do to make it work better? Did one of u guys tried it and it worked smooth?

**Comment by torch2424** [comment]
Hello!

Yes unfortunately, whenever a song ends, the stream does end (for about 2 seconds) to grab a new song and gif, and start streaming once more. 

I got multi-streams working by using Nginx and I mention it at #18 , but have yet to take the time to code that up.

I personally haven't used restream, but if that is a problem for them to keep re connecting, then it may not work 😞

**Comment by torch2424** [comment]
Closing this from no response. Please try version 2.0.0, it still does the short stream disconnect when switching songs but I've noticed it to be much faster.

Hope that helps, thanks!
