### ISSUE TITLE
Well still not working, gonna paste the whole code stuff here.

### ISSUE THREAD

**Issue by ammarr00** [torch2424/piStreamRadio#31]
`pi@raspberrypi:~/piStreamRadio` $ ./startStream.sh
 
 
--------------------------------------------------
Please wait while we initialize the stream...
--------------------------------------------------
 
 
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.9.80-v7+/modules.dep.bin'
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.9.80-v7+
./optimizeGif.sh: line 24: ffmpeg: command not found
./optimizeGif.sh: line 29: ffmpeg: command not found
gifsicle:<stdin>: empty file
 
 
--------------------------------------------------
Starting the stream...
--------------------------------------------------
 
 
./startStream.sh: line 56: ${#(date +%s) % $RADIO_INTERLUDE_INTERVAL_LENGTH }: bad substitution
pi@raspberrypi:~/piStreamRadio $ 
``

**Comment by ammarr00** [comment]
Here is the optimizeGif.sh file
#!/bin/bash

# Script to generate an optimized gif
if [ "$#" -ne 2 ]; then
  echo "optimizeGif.sh: Opinionated Bash Script to optimize a gif"
  echo " "
  echo "USAGE: ./optimizeGif.sh [input.gif] [output.gif]"
  echo " "
else

  # Define our variables
  GIF=$1
  OPTIMIZED_GIF_PATH=$2
  PALLET_PATH="/tmp/optimizeGifPallet.png"

  # Import our config
  source radioFiles/config.sh

  # Optimize the gif to be small no larger than the maxsize on the x or y
  # And use gifsicle to reduce filesize
  # See the article: http://blog.pkh.me/p/21-high-quality-gif-with-ffmpeg.html

  # Generate our gif pallete
  ffmpeg -i "$GIF" \
  -vf "fps=$VIDEO_FPS,palettegen=stats_mode=diff" \
  -y "$PALLET_PATH"

  # Use our pallete for a dope optimized gif
  ffmpeg -i "$GIF" \
  -i "$PALLET_PATH" \
  -lavfi "fps=$VIDEO_FPS,scale=w=$MAX_GIF_SIZE:h=$MAX_GIF_SIZE:force_original_aspect_ratio=decrease \
  [x]; [x][1:v] paletteuse=dither=sierra2_4a" \
  -f gif - | gifsicle --optimize=3 --delay=6 > "$OPTIMIZED_GIF_PATH"
fi

**Comment by ammarr00** [comment]
Here is the startStream.sh file
#!/bin/bash

# Source our config files
source radioFiles/config.sh

# Introuduce the program to the user
echo " "
echo " "
echo "--------------------------------------------------"
echo "Please wait while we initialize the stream..."
echo "--------------------------------------------------"
echo " "
echo " "

# Ensure our alsa is allowing for a looped recording
sudo modprobe snd-aloop pcm_substreams=1

# Set our ffmpeg to our PATH
source exportFFmpegToPath.sh

# Allow for CTRL+C to exit
trap "exit" SIGINT

# Define Our Private Temporary Variables
STREAM_GIF_PATH="/tmp/streamGif"
CURRENT_GIF_PATH="/tmp/CURRENT_GIF.txt"
STREAM_TEXT_PATH="/tmp/stream.txt"
CURRENT_GIF=""
RANDOM_SONG=""
ARTIST=""
SONG_NAME=""

# Generate an optimized gif
CURRENT_GIF="$STREAM_GIF_PATH$(date +%s).gif"
echo "$CURRENT_GIF" > "$CURRENT_GIF_PATH"
RANDOM_GIF=$(./getFileFromDir.sh "$GIF_DIRECTORY")
./optimizeGif.sh "$RANDOM_GIF" "$CURRENT_GIF"

echo " "
echo " "
echo "--------------------------------------------------"
echo "Starting the stream..."
echo "--------------------------------------------------"
echo " "
echo " "

while true ; do

      # Source our config files (Before every play)
      source radioFiles/config.sh

      # Initialize our random song
      RANDOM_SONG=""

      # Check if we support interludes, and we should show one
      if [ "$RADIO_INTERLUDES" = true ] && [ "${#(date +%s) % $RADIO_INTERLUDE_INTERVAL_LENGTH }" = 0 ]; then
        # Get our random song
        RANDOM_SONG=$(./getFileFromDir.sh "$INTERLUDE_DIRECTORY")

        # Create our video text from the random song
        rm $STREAM_TEXT_PATH
        echo "$INTERLUDE_TEXT" >> "$STREAM_TEXT_PATH"
      else
        # Get our random song
        RANDOM_SONG=$(./getFileFromDir.sh "$MUSIC_DIRECTORY")

        # Create our video text from the random song
        rm $STREAM_TEXT_PATH
        ARTIST=$(id3info "$RANDOM_SONG" | grep TPE1 | head -n 1 | perl -pe 's/.*: //g')
        SONG_NAME=$(id3info "$RANDOM_SONG" | grep TIT2 | head -n 1 | perl -pe 's/.*: //g')
        echo "Artist: $ARTIST" >> "$STREAM_TEXT_PATH"
        echo " " >> /tmp/stream.txt
        echo "Song: $SONG_NAME" >> "$STREAM_TEXT_PATH"
      fi

      # Create our two threads of audio playing, and the stream
      # Run the commands, and wait for either to finish
      # Also, optimize the next gif, while the stream is playing
      ( /usr/bin/mpg123 "$RANDOM_SONG" ) & \
      ( ./runFfmpeg.sh "$(cat "$CURRENT_GIF_PATH")" "$STREAM_TEXT_PATH" &
      sleep 2; \
      CURRENT_GIF="$STREAM_GIF_PATH$(date +%s).gif"; \
      echo "$CURRENT_GIF" > "$CURRENT_GIF_PATH"; \
      RANDOM_GIF=$(./getFileFromDir.sh "$GIF_DIRECTORY"); \
      ./optimizeGif.sh "$RANDOM_GIF" "$CURRENT_GIF" &
      wait ) & wait -n

      # Kill the other command if one finishes
      pkill -P $$
      # Ensure all three are completely killed (Fixes Alsa device busy)
      sudo killall ffmpeg
      sudo killall mpg123
      sudo killall generateGif

      # Loop to the next song
      echo " "
      echo " "
      echo "--------------------------------------------------"
      echo "Playing next song..."
      echo "--------------------------------------------------"
      echo " "
      echo " "
done

**Comment by karimamer** [comment]
if you have a fix can you add a pull request with it ?  if you don't or can't  i will work on this

**Comment by ammarr00** [comment]
@Karimamer
I need a fix for this

**Comment by ammarr00** [comment]
@karimamer Have you had a chance to look into the problem yet?

**Comment by frozenlq** [comment]
I have the same issue.

**Comment by fsilvestre90** [comment]
Have you had a chance to look into it?

**Comment by torch2424** [comment]
@karimamer I don't mind testing the changes on a pi I have at home 😄

**Comment by fsilvestre90** [comment]
pls respond

**Comment by karimamer** [comment]
@fsilvestre90 
https://media.giphy.com/media/xR9mRg8fFx7C8/giphy.gif

**Comment by torch2424** [comment]
So my apologies, @karimamer and I have been super busy lately, but I just remembered I made a stable release here: https://github.com/torch2424/piStreamRadio/releases/tag/1.0

Try following the instructions again, but with this release, and see how that goes. Thanks!

**Comment by ammarr00** [comment]
@torch2424 how would i do that?

**Comment by torch2424** [comment]
Oh I just saw this my apologies! 

You should be able to just download the zip from the link I posted, extract it, and follow the normal setup 😄 

Thanks!

**Comment by torch2424** [comment]
Hello!

Did you ever figure this out? I just posted a bunch of fixes directly to the master branch. The release should have worked, but if not, feel free to try re-installing.

Thanks!

**Comment by torch2424** [comment]
Closing this because no response, and 2.0.0 rebuilds everything. Please try with the new version coming soon!
