### ISSUE TITLE
How can i stream videos instead of gif?

### ISSUE THREAD

**Issue by EliteDaMyth** [torch2424/piStreamRadio#34]

**Comment by torch2424** [comment]
Hello! I'd have to update the repo to get this working. 

I actually JUST finished school a few days ago. So I should have a bit more time now, though I am currently focused on some other side projects. 

Please feel free to open a PR with this functionality, and we can totally get it pulled in. Thanks!

**Comment by torch2424** [comment]
Version 2.0.0 is coming out soon and supported this. Please see that once it comes out.

Thank you! 👍
