### ISSUE TITLE
Sound issues

### ISSUE THREAD

**Issue by sktwentysix** [torch2424/piStreamRadio#35]
First off, this is a pretty neat little package. Thanks for setting up this repo up!

Running the startStream shell script seems to work, I can see the default gif and title and song info appearing live during the stream. Works very well! ...except for the audio.

There is no sound whatsoever. I tested my own tracks, as well as the default that came with the repo.

EDIT: I should also mention it's a RPi3 with standard Raspian

**Comment by torch2424** [comment]
Hello! 

Thank you! Glad you like it! I actually plan on working on updating this soon. Just moved and started a new job, so been quite busy!

I am pretty sure it's going to be something weird in the ALSA config, can you [check out the original reddit guide this is based on](https://www.reddit.com/r/raspberry_pi/comments/61ntji/247_youtube_music_live_stream_and_how_you_can/), and check out Step 5, which covers ALSA.

Let me know how that goes! :)

**Comment by torch2424** [comment]
Hello! Was this ever resolved? I also made a bunch of fixes on the master branch recently, that may also help with your issue.

Thank you!

**Comment by torch2424** [comment]
Closing this from no response, and version 2.0.0 is coming soon, which should fix this. Please try when it verision 2.0.0 is release 😄 Thank you!
