### ISSUE TITLE
./startStream.sh: source: not found

### ISSUE THREAD

**Issue by Trobyss** [torch2424/piStreamRadio#39]
Hi ! i have this error in boucle when i launch the script...

```
./startStream.sh: 4: ./startStream.sh: source: not found


--------------------------------------------------
Please wait while we initialize the stream...
--------------------------------------------------


./startStream.sh: 19: ./startStream.sh: source: not found
trap: SIGINT: bad trap
find: ‘’: No such file or directory
ffmpeg version git-2018-09-16-5109c38 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --enable-shared --prefix=/usr
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 30.100 / 58. 30.100
  libavformat    58. 18.101 / 58. 18.101
  libavdevice    58.  4.103 / 58.  4.103
  libavfilter     7. 32.100 /  7. 32.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
/: Is a directory
ffmpeg version git-2018-09-16-5109c38 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --enable-shared --prefix=/usr
  libavutil      56. 19.101 / 56. 19.101
  libavcodec     58. 30.100 / 58. 30.100
  libavformat    58. 18.101 / 58. 18.101
  libavdevice    58.  4.103 / 58.  4.103
  libavfilter     7. 32.100 /  7. 32.100
  libswscale      5.  2.100 /  5.  2.100
  libswresample   3.  2.100 /  3.  2.100
/: Is a directory
gifsicle:<stdin>: empty file


--------------------------------------------------
Starting the stream...
--------------------------------------------------


./startStream.sh: 50: ./startStream.sh: source: not found
find: ‘’: No such file or directory
./startStream.sh: 86: wait: Illegal option -n
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.23.8; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes
./runFfmpeg.sh: line 19: .radioFiles/config.sh: No such file or directory
./runFfmpeg.sh: line 24: ${#VIDEO_FPS \* 3}: bad substitution

mpg123: death by SIGTERM
ffmpeg: no process found
generateGif: no process found
```

Thanks !

**Comment by torch2424** [comment]
Huh, seems like that the `source` command is not found. if I may ask, are you running this as the pi user?

Thanks!

**Comment by Trobyss** [comment]
hi ! 
I check when I come back but it seems to me that yes ...

**Comment by Trobyss** [comment]
Hi ! i solve my problems but i have new one:

./radioFiles/gifs/./radioFiles/gifs/.DS_Store: No such file or directory
./runFfmpeg.sh: line 19: .radioFiles/config.sh: No such file or directory
./runFfmpeg.sh: line 24: ${#VIDEO_FPS \* 3}: bad substitution
[src/libmpg123/readers.c:1182] error: Cannot open file
./radioFiles/music/./radioFiles/music: No such file or directory
main: [src/mpg123.c:732] error: Cannot open
./radioFiles/music/./radioFiles/music: File access error. (code 22)
./startStream.sh: line 103:  2431 Terminated              ( ./runFfmpeg.sh "$(cat "$CURRENT_GIF_PATH")" "$STREAM_TEXT_PATH" & sleep 2; CURRENT_GIF="$STREAM_GIF_PATH$(date +%s).gif"; echo "$CURRENT_GIF" > "$CURRENT_GIF_PATH"; RANDOM_GIF=$(./getFileFromDir.sh "$GIF_DIRECTORY"); ./optimizeGif.sh "$RANDOM_GIF" "$CURRENT_GIF" & wait )

**Comment by torch2424** [comment]
Hello,

Glad you figured it out! If I may ask, perhaps your project clone got messed up? Seems like you are missing your `radioFiles/config.sh`.

Also, some of the neccessary folder were not created, such as your music folder.

Also, are you running the `./startStream.sh` from the project directory? E.g `/home/pi/piStreamRadio` ?

**Comment by torch2424** [comment]
Hello! So I just updated the project. If I could ask, could you try re-installing the project? I ran into similar issues as you trying to do everything from a clean slate, and it should work now 😄

**Comment by Trobyss** [comment]
Hi ! 
Thanks for this update, but i have new error now ahah:

`[h264_omx @ 0x1b41390] err 80001005 (-2147479547) on line 481
Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
[alsa @ 0x1b1eb60] Thread message queue blocking; consider raising the thread_queue_size option (current value: 8)
Conversion failed!
`
and 


`
mpg123: death by SIGTERM
./startStream.sh: line 116:  2056 Terminated              ( ./runFfmpeg.sh "$(cat "$CURRENT_GIF_PATH")" "$STREAM_TEXT_PATH" & sleep 2; CURRENT_GIF="$STREAM_GIF_PATH$(date +%s).gif"; echo "$CURRENT_GIF" > "$CURRENT_GIF_PATH"; RANDOM_GIF=$(./getFileFromDir.sh "$GIF_DIRECTORY"); ./optimizeGif.sh "$RANDOM_GIF" "$CURRENT_GIF" & wait )
./runFfmpeg.sh: line 49:  2064 Terminated              ffmpeg -f alsa -ac 2 -i hw:Loopback,1,0 -fflags +genpts -ignore_loop 0 -r "$VIDEO_FPS" -i "$GIF" -s "$VIDEO_RESOLUTION" -vf "[in]drawtext=   text=:'$STREAM_TITLE':   fontfile=${VIDEO_FONT}:   fontsize=$FONT_SIZE:   bordercolor=$FONT_BORDER_COLOR: borderw=1: fontcolor=$FONT_COLOR:   y=$FONT_TITLE_Y_POS: x=w-mod(max(t\,0)*(w+tw)/$FONT_TITLE_SCROLL_SPEED\,(w+tw)),   drawtext=fontfile=${VIDEO_FONT}:   fontsize=$FONT_SIZE:   fix_bounds=true:   bordercolor=$FONT_BORDER_COLOR: borderw=1: fontcolor=$FONT_COLOR:   textfile=$STREAM_TEXT_PATH: y=$FONT_MUSIC_Y_POS: x=$FONT_MUSIC_X_POS[out]" -vcodec h264_omx -x264opts keyint="$KEYINT":min-keyint="$KEYINT":scenecut=-1 -b:v "$VIDEO_BIT_RATE" -preset veryfast -pix_fmt yuv420p -c:a libfdk_aac -b:a "$AUDIO_BIT_RATE" -bufsize 960k -ar "$AUDIO_SAMPLE_RATE" -f flv "$STREAM_URL"
mpg123: no process found
generateGif: no process found
`

Thanks :) 

Trobyss

**Comment by torch2424** [comment]
Huh. Did you do everything from a clean slate?

Like a fresh install of raspbian, and the project?

I think that will help here, as it seems like ffmpeg and the alsa setup got wacky.

**Comment by torch2424** [comment]
Closing this from no response, and version 2.0.0 will improve a lot of things. Please try the new version once it is release there! 😄
