### ISSUE TITLE
Can not start stream

### ISSUE THREAD

**Issue by DarkGohst** [torch2424/piStreamRadio#43]
On starting stream i get this error:
root@ip56:~/piStreamRadio# ./startStream.sh

--------------------------------------------------
Please wait while we initialize the stream...
--------------------------------------------------

modprobe: ERROR: ../libkmod/libkmod.c:514 lookup_builtin_file() could not open builtin file '/lib/modules/4.13.13-5-pve/modules.builtin.bin'
modprobe: FATAL: Module snd-aloop not found in directory /lib/modules/4.13.13-5-pve
./optimizeGif.sh: line 24: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
./optimizeGif.sh: line 29: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
gifsicle:<stdin>: empty file

--------------------------------------------------
Starting the stream...
--------------------------------------------------

Playing Song:
Path: ./radioFiles/music/Aviscerall - Nostalgia Infinite - 04 Scattered Dreams.mp3
Artist: Aviscerall
Song: Scattered Dreams

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
./runFfmpeg.sh: line 31: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
exec of JACK server (command = "/usr/bin/jackd") failed: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
./optimizeGif.sh: line 24: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
./optimizeGif.sh: line 29: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
gifsicle:<stdin>: empty file
ffmpeg: no process found
./startStream.sh: line 116: 13465 Terminated              ( /usr/bin/mpg123 "$RANDOM_SONG" )
mpg123: no process found
generateGif: no process found

--------------------------------------------------
Playing next song...
--------------------------------------------------

Playing Song:
Path: ./radioFiles/music/Aviscerall - Lp's and Love Songs - 01 I Am a Fool for Beauty.mp3
Artist: Aviscerall
Song: I Am a Fool for Beauty

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
./runFfmpeg.sh: line 31: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
exec of JACK server (command = "/usr/bin/jackd") failed: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
./optimizeGif.sh: line 24: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
./optimizeGif.sh: line 29: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
gifsicle:<stdin>: empty file
ffmpeg: no process found
./startStream.sh: line 116: 13509 Terminated              ( /usr/bin/mpg123 "$RANDOM_SONG" )
mpg123: no process found
generateGif: no process found

--------------------------------------------------
Playing next song...
--------------------------------------------------

Playing Song:
Path: ./radioFiles/music/nestedDirectoriesWork/Aviscerall - Cruisin' - 01 Sanctuary.mp3
Artist: Aviscerall
Song: Sanctuary

Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
./runFfmpeg.sh: line 31: /root/piStreamRadio/ffmpeg/ffmpeg: cannot execute binary file: Exec format error
exec of JACK server (command = "/usr/bin/jackd") failed: No such file or directory
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel

Can you elp me to fix?

**Comment by torch2424** [comment]
Hello! Seems like the project wasn't installed correctly. Could you try re installing? And did you run `./installDeps.sh` ?

**Comment by torch2424** [comment]
Closing this from no response. Version 2.0.0 is coming soon, please try again with the new version! 😄
